# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('keyword', models.CharField(max_length=256, verbose_name='关键字')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=256, verbose_name='模块')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='Prd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='需求名称')),
                ('prd_url', models.CharField(default='', max_length=256, verbose_name='需求地址')),
            ],
            options={
                'verbose_name': '需求名称',
                'verbose_name_plural': '需求名称',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.User'),
        ),
        migrations.AddField(
            model_name='case',
            name='prd_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Prd'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.User'),
        ),
    ]
