# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=256, verbose_name='模块')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求123',
            },
        ),
        migrations.CreateModel(
            name='Prd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='需求名称')),
                ('prd_url', models.CharField(default='', max_length=256, verbose_name='需求地址')),
            ],
            options={
                'verbose_name': '需求名称',
                'verbose_name_plural': '需求名称',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='column',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.AddField(
            model_name='case',
            name='prd_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Prd', verbose_name='归属需求'),
        ),
    ]
