# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20170506_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '用例', 'verbose_name_plural': '测试用例'},
        ),
    ]
